### ISSUE TITLE
left-over column in compareScenarios2()?

### ISSUE THREAD

**Issue by 0UmfHxcvx5J7JoaOhFSs5mncnisTJJ6q** [pik-piam/remind2#158]
This code 
https://github.com/pik-piam/remind2/blob/2d9b5cd93c3b7b27779999cd71c909e7e1eb66d2/inst/markdown/compareScenarios2/cs2_main.Rmd#L209-L247
leaves the `gdp` column in the `data` tibble.  I suppose it is needed for
https://github.com/pik-piam/remind2/blob/2d9b5cd93c3b7b27779999cd71c909e7e1eb66d2/inst/markdown/compareScenarios2/cs2_plot_functions.R#L344-L401
or could it be removed?

**Comment by chroetz** [comment]
The `gdp` column is left there intentionally. It is used in the function [showMultiLinePlotsByGDP()](https://github.com/pik-piam/remind2/blob/5ad6d0c4988558839d0fb68e62fa4de8e811d868/inst/markdown/compareScenarios2/cs2_plot_functions.R#L344), where it plots are created with `gdp` on the x-axis. But it is not necessarily a particularly elegant solution. It might be better to change `showMultiLinePlotsByGDP()` to a more general `showMultiLinePlotsByVariable()`, in which the user can choose a second variable, the one for the x-axis, and the function itself makes the necessary transformations to get the respective new column so that the 'globally' calculated gdp column can be dropped.
