### ISSUE TITLE
CDR = "off" lets LCOE reporting fail

### ISSUE THREAD

**Issue by orichters** [pik-piam/remind2#236]
With `CDR = off` in REMIND, so not the default `DAC`, the LCOE reporting fails:
```
[1] "start generation of LCOE reporting"
Joining, by = "tech"
Joining, by = c("region", "tech", "rlf")
Joining, by = c("region", "tech")
Error in .dimextract(x, k, 3, pmatch = pmatch, invert = invert) :
  subscript out of bounds ("dac")
In addition: There were 40 warnings (use warnings() to see them)
[1] "end generation of LCOE reporting"
```
Would be great if this was changed. I'm tagging the authors of `reportLCOE.R`.

**Comment by robertpietzcker** [comment]
I think this is the same problem as before - simply add dac to te2rlf, and then it will likely work.
I don't understand why dac should not be included in te2rlf?!

**Comment by orichters** [comment]
Ok, @robertpietzcker, I guess you know that much better than I do, so let's do that :)

**Comment by robertpietzcker** [comment]
Actually, I am now confused. 
after a comment from Kasha, I realized that dac is only in all_te and not in te when CDR is off. 
so I don't understand why reportLCOE sees dac in te at all?

**Comment by katarkow** [comment]
The error is thrown [here](https://github.com/pik-piam/remind2/blob/e6f2e15e8d1849f20246d1e83a196baa4c84f555/R/reportLCOE.R#L904), because `p_teAnnuity` is defined over `te`, where `dac` is not included.

Another problem with no CDR, [a few lines below](https://github.com/pik-piam/remind2/blob/e6f2e15e8d1849f20246d1e83a196baa4c84f555/R/reportLCOE.R#L907), is that the energy demand for DAC (`p33_dac_fedem_el` and `p33_dac_fedem_heat`) is not defined.

**Comment by robertpietzcker** [comment]
ok, so the problem is that there are specific calculations for dac which then break when dac is turned off and (currently) not included in the sets. 

you could make this part of the reporting module-dependent, like the FE reporting is for transport/buildings/industry. 
Or add dac to te (and provide all necessary inputs) and force it to 0.
I don't have a strong opinion which way is better

**Comment by orichters** [comment]
Personally, I would opt for letting it in the reporting, because if you run some scenarios with DAC and others without, you would rather have these number be set to zero than not have them in the reporting.

**Comment by fschreyer** [comment]
Hi all, 

well this is a general problem of reportLCOE that it is not routinely tested when people make changes to REMIND or the reporting. So far, I think I was the only person using that script and I always solved compatibility issues from parameter/variable renamings etc. when I needed the script but not regularly.

**Comment by katarkow** [comment]
@fschreyer, thanks for reviewing my changes!
