### ISSUE TITLE
REMIND reports negative fossil industry emissions

### ISSUE THREAD

**Issue by 0UmfHxcvx5J7JoaOhFSs5mncnisTJJ6q** [pik-piam/remind2#520]
```
> library(tidyverse)
> library(quitte)
> d <- read.quitte('/p/projects/remind/modeltests/remind/output/SSP2EU-NPi-AMT_2024-02-02_22.08.54/REMIND_generic_SSP2EU-NPi-AMT.mif')
> d %>% filter(grepl('^Emi\\|CO2\\|Energy\\|Demand\\|Industry\\|Chemicals\\|.*\\|Fossil$', variable), 0 > value) %>% df_variation() %>% arrange(period, region)
# A tibble: 98 × 4
   region variable                                                 period  value
   <fct>  <fct>                                                     <int>  <dbl>
 1 LAM    Emi|CO2|Energy|Demand|Industry|Chemicals|Solids|+|Fossil   2005 -1.69 
 2 OAS    Emi|CO2|Energy|Demand|Industry|Chemicals|Solids|+|Fossil   2005 -0.618
 3 EUR    Emi|CO2|Energy|Demand|Industry|Chemicals|Solids|+|Fossil   2015 -0.284
 4 CAZ    Emi|CO2|Energy|Demand|Industry|Chemicals|Solids|+|Fossil   2020 -3.33 
 5 LAM    Emi|CO2|Energy|Demand|Industry|Chemicals|Solids|+|Fossil   2020 -1.63 
 6 OAS    Emi|CO2|Energy|Demand|Industry|Chemicals|Solids|+|Fossil   2020 -1.29 
 7 SSA    Emi|CO2|Energy|Demand|Industry|Chemicals|Solids|+|Fossil   2020 -0.889
 8 USA    Emi|CO2|Energy|Demand|Industry|Chemicals|Solids|+|Fossil   2020 -3.37 
 9 CAZ    Emi|CO2|Energy|Demand|Industry|Chemicals|Solids|+|Fossil   2025 -3.28 
10 LAM    Emi|CO2|Energy|Demand|Industry|Chemicals|Solids|+|Fossil   2025 -2.18 
# ℹ 88 more rows
# ℹ Use `print(n = ...)` to see more rows
```

**Comment by 0UmfHxcvx5J7JoaOhFSs5mncnisTJJ6q** [comment]
Since 5 January.
```
$ ls -rt SSP2EU-NPi-AMT_202*/REMIND_generic_SSP2EU-NPi-AMT.mif | tail | xargs grep -c 'Emi|CO2.*Fossil.*;-'
SSP2EU-NPi-AMT_2023-10-27_22.09.15/REMIND_generic_SSP2EU-NPi-AMT.mif:0
SSP2EU-NPi-AMT_2023-11-08_22.08.33/REMIND_generic_SSP2EU-NPi-AMT.mif:0
SSP2EU-NPi-AMT_2023-11-12_04.16.04/REMIND_generic_SSP2EU-NPi-AMT.mif:0
SSP2EU-NPi-AMT_2023-11-17_22.12.06/REMIND_generic_SSP2EU-NPi-AMT.mif:0
SSP2EU-NPi-AMT_2023-12-08_22.09.19/REMIND_generic_SSP2EU-NPi-AMT.mif:0
SSP2EU-NPi-AMT_2023-12-29_22.08.47/REMIND_generic_SSP2EU-NPi-AMT.mif:0
SSP2EU-NPi-AMT_2024-01-05_22.08.21/REMIND_generic_SSP2EU-NPi-AMT.mif:27
SSP2EU-NPi-AMT_2024-01-12_22.10.49/REMIND_generic_SSP2EU-NPi-AMT.mif:26
SSP2EU-NPi-AMT_2024-01-26_22.09.54/REMIND_generic_SSP2EU-NPi-AMT.mif:25
SSP2EU-NPi-AMT_2024-02-02_22.08.54/REMIND_generic_SSP2EU-NPi-AMT.mif:27
```
:eyes: 
```
$ git log --merges --after=2023-12-29 --before=2024-01-05
commit d30f3cc713fcdbd6b6d369f6c067282db8943481
Merge: bb3bd38 0c83272
Author: tabeado <117268634+tabeado@users.noreply.github.com>
Date:   Thu Jan 4 16:02:07 2024 +0100

    Merge pull request #502 from tabeado/master
    
    bugfix dac and ew emissions

commit bb3bd383171892f1a897ab353e6c2c7a92ce5125
Merge: ff50a96 d875e21
Author: tabeado <117268634+tabeado@users.noreply.github.com>
Date:   Thu Jan 4 14:45:33 2024 +0100

    Merge pull request #492 from tabeado/master
    
    adding average LCOccsinje and adjustment cost bugfixes

commit 2164f40fa5be7c02b09ae274550267f7528dc4b3
Merge: 78efc63 ff50a96
Author: tabeado <tabea.dorndorf@pik-potsdam.de>
Date:   Thu Jan 4 13:59:04 2024 +0100

    Merge branch 'master' of https://github.com/pik-piam/remind2

commit ff50a96dc4358f6bc29cb470074ee3f5f6a04ee7
Merge: 09b72be 8593f4a
Author: Falk Benke <69258269+fbenke-pik@users.noreply.github.com>
Date:   Thu Jan 4 13:34:05 2024 +0100

    Merge pull request #501 from fbenke-pik/master
    
    fix errors and warnings in reportEmi
```

**Comment by fbenke-pik** [comment]
This was a fix to make sure that buildLibrary is working again so others could merge their work, as @mellamoSimon forgot to do it with his PR. 

Simón, please take a look and find a solution that also works with buildLibrary.

**Comment by mellamoSimon** [comment]
ok, I'll do that.

**Comment by 0UmfHxcvx5J7JoaOhFSs5mncnisTJJ6q** [comment]
> This was a fix to make sure that buildLibrary is working again so others could merge their work, as @mellamoSimon forgot to do it with [his PR](https://github.com/pik-piam/remind2/pull/489).
> 
> See also: [#489 (comment)](https://github.com/pik-piam/remind2/pull/489#discussion_r1440656520)

That was a pretty stupid fix.

**Comment by fbenke-pik** [comment]
> That was a pretty stupid fix.

What can I say. You were on vacation, so I guess smart fixes were not an option. Would have also helped I you had not approved the PR without buildLibrary in the first place.  

But seriously, if you have nothing productive to contribute, better say nothing.

**Comment by mellamoSimon** [comment]
hey guys,
I take full responsibility. I was in a rush and wasn't careful when merging the feedstocks reporting changes. I agree that now we should focus on fixing this. And we should also stay kind. 
I prepared this draft PR https://github.com/pik-piam/remind2/pull/523 that re-introduces that condition. I didn't have to change anything else so I don't know why that was a problem before. Now I still need to fix the inconsistencies in emissions reporting...rn I'm testing if re-introducing this condition makes any difference. I will keep you updated.

**Comment by mellamoSimon** [comment]
>.rn I'm testing if re-introducing this condition makes any difference. I will keep you updated.

nope, it doesn't... which makes sense.

**Comment by mellamoSimon** [comment]
thank you! That looks reasonable. I was blindly trying to define the required sets to get it running but it would have probably just produced nonsense. 
@fschreyer will need to have a look anyway.

**Comment by 0UmfHxcvx5J7JoaOhFSs5mncnisTJJ6q** [comment]
> This was a fix to make sure that buildLibrary is working again so others could merge their work, as @mellamoSimon forgot to do it with [his PR](https://github.com/pik-piam/remind2/pull/489).
> 
> See also: [#489 (comment)](https://github.com/pik-piam/remind2/pull/489#discussion_r1440656520)

What was bugging me: the Ariadne .gdx is totally fine with this code, is it used the `subsectors` realisation, not `fixed_shares`.

**Comment by 0UmfHxcvx5J7JoaOhFSs5mncnisTJJ6q** [comment]
> > That was a pretty stupid fix.
> 
> What can I say. You were on vacation, so I guess smart fixes were not an option. Would have also helped I you had not approved the PR without buildLibrary in the first place.
> 
> But seriously, if you have nothing productive to contribute, better say nothing.

That was uncalled for, and I would like to apologise for it.

**Comment by fbenke-pik** [comment]
> > > That was a pretty stupid fix.
> > 
> > 
> > What can I say. You were on vacation, so I guess smart fixes were not an option. Would have also helped I you had not approved the PR without buildLibrary in the first place.
> > But seriously, if you have nothing productive to contribute, better say nothing.
> 
> That was uncalled for, and I would like to apologise for it.

Apology accepted :)

**Comment by fbenke-pik** [comment]
> No, buildLibrary() did not run successfully on these changes, else it would have updated the package version. https://github.com/pik-piam/remind2/pull/489/files

Correct. I think what Simón meant is that all tests calling convGDX2MIF are silently skipped if you don't have the proper library setup: 
`  skip_if_not(as.logical(gdxrrw::igdx(silent = TRUE)), "gdxrrw is not initialized properly")`

This is because we haven't found a way to have the gdx libraries running in the Github workflows. It is all well, if you have the gdx libs installed locally and run buildLibrary. Otherwise, bugs can make it into the master branch. Not an optimal solution for sure.

**Comment by mellamoSimon** [comment]
>No, buildLibrary() did not run successfully on these changes, else it would have updated the package version

no no, I meant for the changes of that PR (https://github.com/pik-piam/remind2/pull/523). The other one (https://github.com/pik-piam/remind2/pull/489) is where I just forgot to run `buildLibrary()` and unleashed hell...

**Comment by mellamoSimon** [comment]
Hi there,
so I think that eventually this problem can be traced back to `remind`. In particular, to the way we report energy demand at the subsectoral level with secondary energy carrier details. If I get it right from the code, we cannot really trace back subsectoral demand to the original secondary energy carrier and I think this issue is an artifact of the trick we use to do so. 
So we basically assume that final energy (e.g., `fesos`) distributes homogenously over the possible secondary energy carriers (`sesofos` and `sesobio`) for a given subsector: we apply the same share `o37_shIndFE` to `vm_demFeSector_afterTax` for all possible secondary sources. The problem is that `vm_demFENonEnergySector` is now giving away this (dirty?) trick because it is subsector-specific (basically, it is defined for chemicals only). Then, for example, if in a given region for a given timestep, like the ones in the example above, it turns out that all `fesos` used as feedstock comes from `sesofos` (which in this case it is actually a result of the variables that participate in the optimization problem) and none from `sesobio`, the *postprocessing* will still allocate a part of this energy to `sesobio` when calculating total `feso` demand in the chemicals subsector (`o37_demFeIndSub`). This results in the reporting trick assigning a lower value `o37_demFeIndSub(sesofos,feso)` than it actually has or can have. Later, when this variable gets passed on to `remind2`, we calculate energy flows without feedstocks (`o37_demFeIndSub_woNonEn`) [here](https://github.com/pik-piam/remind2/blob/d423258f33ded235718d77c185af51f66a7d6158/R/reportEmi.R#L671) and that variable will take negative values because the trick-calculated total FE demand (`o37_demFeIndSub(sesofos,feso)`) is too low. Then, when we multiply a negative energy flow by the emission factor, we get these negative emissions. 
This is just my working hypothesis at the moment, please feel free to refute it. If this is true, I see 2 possible solutions: (1) we get rid of those reported variables because they are anyway artificial or (2) in remind's post-processing, we separate the calculations for the chemicals subsector and allocate secondary sources independently for energy- and feedstock-use of energy carriers.

**Comment by 0UmfHxcvx5J7JoaOhFSs5mncnisTJJ6q** [comment]
> (1) we get rid of those reported variables because they are anyway artificial

Not an option.  These variables are required to disaggregate what is going on in industry.

**Comment by fschreyer** [comment]
Hey Simon, 

thanks for looking into that. It makes sense to me. it would also go for option 2). As you say, I think that could be done by restricting the calculation of FE per industry subsector in the postsolve.gms to FE excluding non-energy use. So, the non-energy use FE should be subtracted in the calculations of ``o37_demFeIndTotEn``, ``o37_shIndFE`` and ``o37_demFeIndSub`` if I see correctly. Then, o37_shIndFE would only be the share of a sector in total FE for energy that is actually combusted. Afterwards, [these two lines](https://github.com/pik-piam/remind2/blob/f977fd850d796e2d3a1cb485f2b263ec9011c59e/R/reportEmi.R#L670) in the emissions reporting, I believe, would need to be deleted as ``o37_demFeIndSub`` will already be w/o non-energy use (maybe even rename the parameter for clarity). Hope I don't overlook something, but that would be my idea.
